services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data
volumes:
  mongodb_data:

# Build compose
# docker-compose -f dockercompose.yaml build

# Run compose
# docker-compose -f dockercompose.yaml up